name: test_workflow

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - run: javac HelloWorld.java
    - run: java HelloWorld
